### ISSUE TITLE
Merge makeModel with pfeiffer branch?

### ISSUE THREAD

**Issue by patrickvonplaten** [patrickvonplaten/TRexGameRL#13]

**Comment by kilsenp** [comment]
pfeiffer branch was my personal development branch that I would usually delete. So I am not sure why it should be merged with some other branch after it was already merged to master.

**Comment by patrickvonplaten** [comment]
then delete makeModel?

**Comment by kilsenp** [comment]
I deleted pfeiffer, you can delete makeModel in case you don't need it anymore!
