### ISSUE TITLE
Why is deque function in preprocessor changed to numpy concatenate? -> buffer should have the functioning of a queue, no?

### ISSUE THREAD

**Issue by patrickvonplaten** [patrickvonplaten/TRexGameRL#14]

**Comment by kilsenp** [comment]
Keras model expects a numpy array that a conversion of the deque structure to a numpy array would be necessary.
I'd argue that it is nicer to have a pure numpy implementation than to convert between data structures.
The buffer logic is no implemented in numpy..
https://github.com/patrickvonplaten/TRexGameRL/blob/master/python/tRexManager.py#L317
Takes all rows but the first, concatenates a new element at the end.
