### ISSUE TITLE
save and visualize train metrics, train history, think about new metrics to log: avg actions per epoch, avg reward per epoch, ...?

### ISSUE THREAD

**Issue by patrickvonplaten** [patrickvonplaten/TRexGameRL#23]

**Comment by kilsenp** [comment]
Yes, that would be interesting to see. I'd suggest something like:
- loss
- all running parameters like exploration factor
- ingame score
- maybe average of reward prediction (in theory that should increase, right?)
- jumps per epochs, later also ducks

**Comment by patrickvonplaten** [comment]
added a logger class 
I think adding jumps per epochs & average reward would be nice!

**Comment by patrickvonplaten** [comment]
Added two new metrics:
- avg_q_value (average expected max total reward given from the Q function) 
- sum_of_reward over one epoch
